---
- name: Install dependencies
  hosts: localhost
  tasks:
    # General dependencies
    - name: Install formulae
      community.general.homebrew:
        name:
          - bat
          - eza
          - fd
          - fzf
          - gh
          - git-delta
          - gnu-sed
          - go
          - helm
          - hub
          - k9s
          - krew
          - kubectx
          - lazygit
          - luarocks
          - lychee
          - neovim
          - pngpaste
          - ripgrep
          - stern
          - terraform-docs
          - the_silver_searcher
          - tmux
          - tmux-mem-cpu-load
          - vim
          - zoxide
        state: present
      tags: brew

    - name: Install casks
      community.general.homebrew_cask:
        name:
          - alt-tab
          - docker
          - firefox@developer-edition
          - font-jetbrains-mono-nerd-font
          - hiddenbar
          - keymapp
          - nikitabobko/tap/aerospace
          - obsidian
          - raycast
          - stats
          - wezterm@nightly
        state: present
      tags: brew

    - name: create /usr/local/bin
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: "0755"
      become: true

    # vim
    - name: Symlink vim directory and running configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        state: link
      loop:
        - vim
        - vimrc
      tags: vim
    - name: Create vim directories
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - undo
        - backup
        - swap
      tags: vim

    # nvim
    - name: Symlink nvim directory and running configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
      loop:
        - nvim
      tags: nvim

    # gh
    - name: Check if gh-notify extension is already installed
      ansible.builtin.command: gh ext list
      register: gh_ext_list
      changed_when: false
      tags: gh
    - name: Install gh notify extension
      ansible.builtin.command: gh ext install meiji163/gh-notify
      when: "'meiji163/gh-notify' not in gh_ext_list.stdout"
      tags: gh

    # shell-color-scripts
    - name: Check if shell-color-scripts is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/random-splash
      register: shell_color_scripts_installed
      tags: shell-color-scripts
    - name: Clone shell-color-scripts repository
      ansible.builtin.git:
        repo: https://gitlab.com/dwt1/shell-color-scripts.git
        dest: /tmp/shell-color-scripts
      when: not shell_color_scripts_installed.stat.exists
      tags: shell-color-scripts
    - name: Install shell-color-scripts
      ansible.builtin.command: make install
      args:
        chdir: /tmp/shell-color-scripts
      when: not shell_color_scripts_installed.stat.exists
      become: true
      tags: shell-color-scripts

    # tmux
    - name: Symlink tmux configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/tmux/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        state: link
      loop:
        - tmux.conf
        - tmuxline
      tags: tmux
    - name: Check if tpm is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
      register: tpm_installed
      tags: tmux
    - name: Install tpm
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
      when: not tpm_installed.stat.exists
      tags: tmux
    - name: Check if getipfortmux is installed
      ansible.builtin.stat:
        path: /usr/local/bin/getipfortmux
      register: getipfortmux_installed
      tags: tmux
    - name: Clone getipfortmux repository
      ansible.builtin.git:
        repo: https://github.com/JoshOldenburg/ipaddrutil.git
        dest: /tmp/ipaddrutil
      when: not getipfortmux_installed.stat.exists
      tags: tmux
    - name: Build getipfortmux
      ansible.builtin.command: make all
      args:
        chdir: /tmp/ipaddrutil
      when: not getipfortmux_installed.stat.exists
      tags: tmux
    - name: Add getipfortmux binary to path
      ansible.builtin.copy:
        src: /tmp/ipaddrutil/getipfortmux
        dest: /usr/local/bin/getipfortmux
        mode: "0755"
      become: true
      when: not getipfortmux_installed.stat.exists
      tags: tmux
    - name: Check if tmux-battery is installed
      ansible.builtin.stat:
        path: /usr/local/bin/tmux-battery
      register: tmux_battery_installed
      tags: tmux
    - name: Clone tmux-battery repository
      ansible.builtin.git:
        repo: https://github.com/JoshOldenburg/tmux-battery.git
        dest: /tmp/tmux-battery
      when: not tmux_battery_installed.stat.exists
      tags: tmux
    - name: Build tmux-battery
      ansible.builtin.command: make all
      args:
        chdir: /tmp/tmux-battery
      when: not tmux_battery_installed.stat.exists
      tags: tmux
    - name: Add tmux-battery binary to path
      ansible.builtin.copy:
        src: /tmp/tmux-battery/tmux-battery
        dest: /usr/local/bin/tmux-battery
        mode: "0755"
      become: true
      when: not tmux_battery_installed.stat.exists
      tags: tmux

    # fzf
    - name: Symlink fzf configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/shell/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        state: link
      loop:
        - fzf.zsh
        - p10k.zsh
      tags: fzf

    # Prezto
    - name: Install prezto
      ansible.builtin.git:
        repo: https://github.com/sorin-ionescu/prezto.git
        dest: "{{ ansible_env.HOME }}/.zprezto"
      tags: prezto
    - name: Symlink prezto configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/shell/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        state: link
      loop:
        - zshrc
        - zpreztorc
      tags: prezto
    - name: Install fzf-tab prezto module
      ansible.builtin.git:
        repo: https://github.com/Aloxaf/fzf-tab
        dest: "{{ ansible_env.HOME }}/.zprezto/contrib/fzf-tab"
      tags: prezto

    # git
    - name: Symlink git configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/git/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        state: link
      loop:
        - gitconfig
      tags: git

    # wezterm
    - name: Symlink wezterm configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/wezterm/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        state: link
      loop:
        - wezterm.lua
      tags: wezterm

    # aerospace
    - name: Create aerospace directories
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - aerospace
      tags: aerospace
    - name: Symlink aerospace configuration
      ansible.builtin.file:
        src: "{{ playbook_dir }}/aerospace/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/aerospace/{{ item }}"
        state: link
      loop:
        - aerospace.toml
      tags: aerospace
